I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 262, in script
    define inner_t = Character("Inner Thought", show_side_image=mainavatar_smile)
  File "game/script.rpy", line 262, in <module>
    define inner_t = Character("Inner Thought", show_side_image=mainavatar_smile)
NameError: name 'mainavatar_smile' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 262, in script
    define inner_t = Character("Inner Thought", show_side_image=mainavatar_smile)
  File "C:\Users\Alvin\Downloads\renpy-6.99.1-sdk\renpy\ast.py", line 1723, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Alvin\Downloads\renpy-6.99.1-sdk\renpy\python.py", line 1456, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 262, in <module>
    define inner_t = Character("Inner Thought", show_side_image=mainavatar_smile)
NameError: name 'mainavatar_smile' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.1.329
AppJam Test 2015 0.0
